version: '3.4'

services:
  app:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    
    env_file:
      - .env
    networks:
      - reverse-proxy