version: '3.4'

services:
  api:
    image: ${REGISTRY}/${API_IMAGE}:${TAG}
    container_name: backend-api
    restart: always
    ports:
      - 8000:8000
    logging:
      driver: syslog
      options:
        tag: "api-production"
    environment:
      - MONGODB_URL
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_NAME
      - SMTP_PASSWORD
      - FRONT_END_URL
      - PASSWORD_SALT
      - JWT_SIGNING_KEY
      - HTTP_HOST

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE}:${TAG}
    container_name: backend-api-proxy
    restart: always
    volumes:
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    environment:
      - API_HOST=api.alphawavetechnology.com
      - API_PORT=8000
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - api
