http:
  port: 8000
  readTimeout: 20s
  writeTimeout: 20s
  maxHeaderBytes: 1

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h
  verificationCodeTTL: 30s
  verificationCodeLength: 10

smtp:
  host: "smtp.gmail.com"
  port: 587
  from: "avalonsendler@gmail.com"

email:
  templates:
    verification: "./templates/verification_email.html"
    forgotPassword: "./templates/forgot_password.html"
  subjects:
    verification: "Thanks, for registration %s!"
    forgotPassword: "Password recovery request"

